# Site settings
title: ViNN
email:
description: > # this means to ignore newlines until "baseurl:"
  ViNN is an OpenCL accelerated deep neural networks library for heterogeneous compute environments.
baseurl: ""
url: "http://www.vinn.io"
twitter_username: ville_ka
github_username:  ville-k

# Build settings
markdown: kramdown
